print("ingrese la cantida de billetes")
billetes=int(input())
print("ingrese la cantidad de monedas")
monedas=int(input())
print("valor de cada billete")
valbill=int(input())
print("ingrese el valor de cada moneda")
valmon=int(input())
total=(billetes*valbill)+(monedas*valmon)
print("el total de la caja registradora es:",total)